### ISSUE TITLE
Unable to run Antennas - SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by jacksummers94** [jfarseneau/antennas#100]
Trying to run Antennas as an alternative to TVHProxy and cannot get it running i have created an user in TVHeadend and still not working just wondering if anyone else has come across the issue?

Commands using: 

npx antennas --config config/config.yml

or

node index.js

Output same error:

```
/usr/local/lib/node_modules/antennas/src/router.js:10
    if (channels?.response?.status === 403) { throw new Error('Username and password not accepted by Tvheadend'); }
                 ^

```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
     at `Object.<anonymous>` (/usr/local/lib/node_modules/antennas/index.js:31:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```
```

**Comment by jacksummers94** [comment]
Update i had to revert back to 4.1 so need to look further into 4.2 on this.

Kind Regards
Jack

**Comment by ardunt** [comment]
I too have this same issue. 
I'm running 4.3-2140~g14298acb6
Have tested also on 4.2.8-36 with the sam error. 
I the anonymous user * has been created in TV, what user:pass details need to go into the config.yml file?
Have tried with none. 
Have also tried creating a user account with required permissions and entering the account details in config.yml, same issue.

**Comment by csharpengineer** [comment]
I had this same issue.  It is because the version of node you are running is out of date.  I updated the version of node I was running with this, YMMV depending on what OS you are running:  https://askubuntu.com/a/480642

**Comment by sammy2142** [comment]
For people using a Raspberry Pi Zero (ARM v6) you can get modern node builds here:
https://github.com/sdesalas/node-pi-zero
