### ISSUE TITLE
TypeError: body.entries is not iterable

### ISSUE THREAD

**Issue by Thomvh** [jfarseneau/antennas#34]
When running the docker file with my TVHeadend setup I get the following error when I try to setup the DVR:

``` <-- POST /lineup.post?scan=start&source=Cable
  --> POST /lineup.post?scan=start&source=Cable 404 2ms -
  <-- GET /discover.json
  --> GET /discover.json 200 3ms 329b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 1ms 77b
  <-- GET /discover.json
  --> GET /discover.json 200 0ms 329b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 0ms 77b
  <-- GET /lineup.json
  xxx GET /lineup.json 500 63ms -

  TypeError: body.entries is not iterable
      at /antennas/src/lineup.js:10:30
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:182:7)
```
And Plex gives the message: "There is an error with receiving your channels."

**Comment by user897943** [comment]
Same here

**Comment by jfarseneau** [comment]
This is hopefully solved now!
