### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by jwrober** [jfarseneau/antennas#97]
I'm getting this error from antennas when trying to add it to Plex DVR.

```
 <-- GET /discover.json
  --> GET /discover.json 200 2ms 388b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 2ms 77b
  <-- GET /lineup.json
  xxx GET /lineup.json 500 2ms -

TypeError: Cannot read properties of undefined (reading 'status')
      at AxiosDigest.getWwwAuth (/home/hts/antennas/antennas/node_modules/axios-digest/index.js:147:33)
      at AxiosDigest.<anonymous> (/home/hts/antennas/antennas/node_modules/axios-digest/index.js:71:53)
      at step (/home/hts/antennas/antennas/node_modules/axios-digest/index.js:33:23)
      at Object.throw (/home/hts/antennas/antennas/node_modules/axios-digest/index.js:14:53)
      at rejected (/home/hts/antennas/antennas/node_modules/axios-digest/index.js:6:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm running tvheadend 4.3.0 on ubuntu 20.04. Using local node setup, not in docker container.

**Comment by HannahRy** [comment]
I'm having this issue too, looks like some issue with the AxiosDigest library. There is a workaround: In TVheadend, change the auth type to Basic (under Config > General > Base > HTTP server settings)

**Comment by no1knows** [comment]
> I'm having this issue too, looks like some issue with the AxiosDigest library. There is a workaround: In TVheadend, change the auth type to Basic (under Config > General > Base > HTTP server settings)

This is now labelled "Plain (insecure)" in settings. Thanks for the pointer!
